# Adding requried libraries
library(alr4)
library(readr)
library(boot)
library(readxl)
View(Insurance_Claim.july)
m1=na.omit(Insurance_Claim.july)
Gender=as.factor(m1$gender)
Region=as.factor(m1$region)
Smoker=as.factor(m1$smoker)
Diabetic=as.factor(m1$diabetic)
pairs(claim~age +Gender+bmi+bloodpressure+Diabetic+children+Smoker+Region,m1 )

m2=lm(claim~age+bmi+Gender+bloodpressure+Diabetic+children+Smoker+Region,m1)
residualPlots(m2)
pt1<-powerTransform(claim~age+bmi+Gender+bloodpressure+Diabetic+children+Smoker+Region,m1)
summary(pt1)
m2=lm(I(claim^ 0.352)~age+bmi+I(bmi^2)+Gender+bloodpressure+Diabetic+children+Smoker+Region,m1)
ncvTest(m2)
cooks.distance(m2)
which.max(cooks.distance(m2))
outlierTest(m2) 

summary(m2)
